Build and Check - separate build dir:
  script:
  - git submodule update --init && make autoreconf && mkdir -p build && cd build && ../configure
    --disable-non-suiteb-curves --with-included-libtasn1 --enable-seccomp-tests --disable-guile --disable-valgrind-tests --disable-doc && make && make check
  - cat tests/test-suite.log
  tags:
  - nettle2
  except:
  - tags
Build and Check with valgrind:
  script:
  - git submodule update --init && make autoreconf && rm -f tests/suite/mini-eagain2.c && ./configure
    --disable-non-suiteb-curves --with-included-libtasn1 --disable-doc --disable-guile && make && make check
  - cat tests/test-suite.log
  tags:
  - x86-64
  - nettle2
  except:
  - tags
Build and Check with asan:
  script:
  - git submodule update --init && make autoreconf && rm -f tests/suite/mini-eagain2.c &&CFLAGS="-fsanitize=address -g
    -O2" LDFLAGS="-static-libasan" ./configure --disable-doc --with-included-libtasn1 --disable-valgrind-tests --disable-non-suiteb-curves --disable-guile
    && make && make check
  - cat tests/test-suite.log
  tags:
  - x86-64
  - nettle2
  except:
  - tags
